# fly.toml app configuration file generated for datingapp2016134773 on 2023-05-24T20:13:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp2016134773"
primary_region = "jnb"

[build]
  image = "nkatekodev/datingapp:latest"

[env]
ASPNETCORE_URLS="http://+:8080"
CloudinarySettings__CloudName="drqxrxsa4"
CloudinarySettings__ApiKey="684648335233748"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
